package com.robotrade.entrypoint;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import org.json.JSONException;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import com.robotrade.authentication.UserAuthentication;
import com.robotrade.controllers.KiteConnectController;
import com.robotrade.service.KiteApiServices;
import com.zerodhatech.kiteconnect.KiteConnect;
import com.zerodhatech.kiteconnect.kitehttp.exceptions.KiteException;
import com.zerodhatech.models.Quote;

@EnableScheduling
@SpringBootApplication
@Component
public class RoboTradeApplication {

    public static String[] instruments = {"NSE:20MICRONS","NSE:21STCENMGM","NSE:3IINFOTECH","NSE:3MINDIA","NSE:3PLAND","NSE:5PAISA","NSE:63MOONS","NSE:A2ZINFRA","NSE:AARTIDRUGS", "NSE:AARTIIND","NSE:AARVEEDEN","NSE:AAVAS","NSE:ABAN","NSE:ABB","NSE:ABBOTINDIA","NSE:ABCAPITAL","NSE:ABFRL","NSE:ABMINTLTD-BE","NSE:ACC","NSE:ACCELYA", "NSE:ACE", "NSE:ADANIENT", "NSE:ADANIGAS", "NSE:ADANIGREEN", "NSE:ADANIPORTS", "NSE:ADANIPOWER", "NSE:ADANITRANS", "NSE:ADFFOODS", "NSE:ADHUNIKIND", "NSE:ADLABS-BE", "NSE:ADORWELD", "NSE:ADROITINFO-BE", "NSE:ADSL-BE", "NSE:ADVANIHOTR", "NSE:ADVENZYMES", "NSE:AEGISCHEM", "NSE:AFFLE", "NSE:AGARIND", "NSE:AGCNET", "NSE:AGRITECH", "NSE:AGROPHOS", "NSE:AHLEAST", "NSE:AHLUCONT", "NSE:AHLWEST", "NSE:AIAENG", "NSE:AIONJSW", "NSE:AIRAN", "NSE:AJANTPHARM", "NSE:AJMERA","NSE:AKSHARCHEM", "NSE:AKSHOPTFBR", "NSE:AKZOINDIA", "NSE:ALANKIT", "NSE:ALBERTDAVD", "NSE:ALBK", "NSE:ALCHEM-BE", "NSE:ALEMBICLTD", "NSE:ALICON", "NSE:ALKALI", "NSE:ALKEM", "NSE:ALKYLAMINE", "NSE:ALLCARGO", "NSE:ALLSEC", "NSE:ALMONDZ", "NSE:ALOKTEXT-BE", "NSE:ALPA", "NSE:ALPHAGEO", "NSE:ALPSINDUS-BE", "NSE:AMARAJABAT", "NSE:AMBER", "NSE:AMBIKCO", "NSE:AMBUJACEM", "NSE:AMDIND", "NSE:AMJLAND", "NSE:AMRUTANJAN", "NSE:ANANTRAJ", "NSE:ANDHRABANK", "NSE:ANDHRACEMT", "NSE:ANDHRSUGAR", "NSE:ANDPAPER", "NSE:ANIKINDS", "NSE:ANKITMETAL", "NSE:ANSALAPI", "NSE:ANSALHSG", "NSE:ANTGRAPHIC", "NSE:ANUP", "NSE:APARINDS", "NSE:APCL", "NSE:APCOTEXIND", "NSE:APEX", "NSE:APLAPOLLO", "NSE:APLLTD", "NSE:APOLLO", "NSE:APOLLOHOSP", "NSE:APOLLOPIPE", "NSE:APOLLOTYRE", "NSE:APOLSINHOT", "NSE:APTECHT", "NSE:ARCHIDPLY", "NSE:ARCHIES", "NSE:ARCOTECH", "NSE:ARENTERP", "NSE:ARIES", "NSE:ARIHANT", "NSE:ARIHANTSUP", "NSE:ARMANFIN", "NSE:AROGRANITE", "NSE:ARROWGREEN", "NSE:ARROWTEX", "NSE:ARSHIYA", "NSE:ARSSINFRA", "NSE:ARTEMISMED", "NSE:ARVIND", "NSE:ARVINDFASN", "NSE:ARVSMART", "NSE:ASAHIINDIA", "NSE:ASAHISONG", "NSE:ASAL", "NSE:ASHAPURMIN", "NSE:ASHIANA", "NSE:ASHIMASYN", "NSE:ASHOKA", "NSE:ASHOKLEY", "NSE:ASIANHOTNR", "NSE:ASIANPAINT", "NSE:ASIANTILES", "NSE:ASPINWALL", "NSE:ASTEC", "NSE:ASTERDM", "NSE:ASTRAL", "NSE:ASTRAMICRO", "NSE:ASTRAZEN", "NSE:ASTRON", "NSE:ATFL", "NSE:ATLANTA", "NSE:ATLASCYCLE", "NSE:ATUL", "NSE:ATULAUTO", "NSE:AUBANK", "NSE:AURIONPRO", "NSE:AUROPHARMA", "NSE:AUSOMENT", "NSE:AUTOAXLES", "NSE:AUTOIND", "NSE:AUTOLITIND", "NSE:AVADHSUGAR", "NSE:AVANTIFEED", "NSE:AVTNPL", "NSE:AXISBANK", "NSE:AXISCADES", "NSE:AYMSYNTEX", "NSE:BAGFILMS", "NSE:BAJAJ-AUTO", "NSE:BAJAJCON", "NSE:BAJAJELEC", "NSE:BAJAJFINSV", "NSE:BAJAJHIND", "NSE:BAJAJHLDNG", "NSE:BAJFINANCE", "NSE:BALAJITELE", "NSE:BALAMINES", "NSE:BALAXI", "NSE:BALKRISHNA", "NSE:BALKRISIND", "NSE:BALLARPUR", "NSE:BALMLAWRIE", "NSE:BALPHARMA", "NSE:BALRAMCHIN", "NSE:BANARBEADS", "NSE:BANARISUG", "NSE:BANCOINDIA", "NSE:BANDHANBNK", "NSE:BANG", "NSE:BANKBARODA", "NSE:BANKINDIA", "NSE:BANSWRAS", "NSE:BARTRONICS", "NSE:BASF", "NSE:BASML", "NSE:BATAINDIA", "NSE:BAYERCROP", "NSE:BBL", "NSE:BBTC", "NSE:BCG", "NSE:BCP", "NSE:BDL", "NSE:BEARDSELL", "NSE:BEDMUTHA", "NSE:BEL", "NSE:BEML", "NSE:BEPL", "NSE:BERGEPAINT", "NSE:BFINVEST", "NSE:BFUTILITIE", "NSE:BGLOBAL", "NSE:BGRENERGY", "NSE:BHAGERIA", "NSE:BHAGYANGR", "NSE:BHAGYAPROP", "NSE:BHANDARI", "NSE:BHARATFORG", "NSE:BHARATGEAR", "NSE:BHARATRAS", "NSE:BHARATWIRE", "NSE:BHARTIARTL", "NSE:BHEL", "NSE:BIGBLOC", "NSE:BIL", "NSE:BILENERGY", "NSE:BINDALAGRO", "NSE:BIOCON", "NSE:BIOFILCHEM", "NSE:BIRLACABLE", "NSE:BIRLACORPN", "NSE:BIRLAMONEY", "NSE:BKMINDST", "NSE:BLBLIMITED", "NSE:BLISSGVS", "NSE:BLKASHYAP", "NSE:BLS", "NSE:BLUEBLENDS", "NSE:BLUEDART", "NSE:BLUESTARCO", "NSE:BODALCHEM", "NSE:BOMDYEING", "NSE:BOROSIL", "NSE:BOSCHLTD", "NSE:BPCL", "NSE:BPL", "NSE:BRFL", "NSE:BRIGADE", "NSE:BRITANNIA", "NSE:BRNL", "NSE:BROOKS", "NSE:BSE", "NSE:BSELINFRA", "NSE:BSL", "NSE:BSOFT", "NSE:BURNPUR", "NSE:BUTTERFLY", "NSE:BVCL", "NSE:BYKE", "NSE:CADILAHC", "NSE:CALSOFT", "NSE:CAMLINFINE", "NSE:CANBK", "NSE:CANDC", "NSE:CANFINHOME", "NSE:CANTABIL", "NSE:CAPACITE", "NSE:CAPLIPOINT", "NSE:CAPTRUST", "NSE:CARBORUNIV", "NSE:CAREERP", "NSE:CARERATING", "NSE:CASTEXTECH", "NSE:CASTROLIND", "NSE:CCHHL", "NSE:CCL", "NSE:CDSL", "NSE:CEATLTD", "NSE:CEBBCO", "NSE:CELEBRITY", "NSE:CELESTIAL", "NSE:CENTENKA", "NSE:CENTEXT", "NSE:CENTRALBK", "NSE:CENTRUM", "NSE:CENTUM", "NSE:CENTURYPLY", "NSE:CENTURYTEX", "NSE:CERA", "NSE:CEREBRAINT", "NSE:CESC", "NSE:CESCVENT", "NSE:CGCL", "NSE:CGPOWER", "NSE:CHALET", "NSE:CHAMBLFERT", "NSE:CHEMBOND", "NSE:CHEMFAB", "NSE:CHENNPETRO", "NSE:CHOLAFIN", "NSE:CHOLAHLDNG", "NSE:CHROMATIC", "NSE:CIGNITITEC", "NSE:CIMMCO", "NSE:CINELINE", "NSE:CINEVISTA", "NSE:CIPLA", "NSE:CKFSL", "NSE:CLEDUCATE", "NSE:CLNINDIA", "NSE:CMICABLES", "NSE:CNOVAPETRO", "NSE:COALINDIA", "NSE:COCHINSHIP", "NSE:COFFEEDAY", "NSE:COLPAL", "NSE:COMPINFO", "NSE:COMPUSOFT", "NSE:CONCOR", "NSE:CONFIPET", "NSE:CONSOFINVT", "NSE:CONTROLPR", "NSE:CORALFINAC", "NSE:CORDSCABLE", "NSE:COROMANDEL", "NSE:CORPBANK", "NSE:COSMOFILMS", "NSE:COUNCODOS", "NSE:COX&KINGS", "NSE:CREATIVE", "NSE:CREATIVEYE", "NSE:CREDITACC", "NSE:CREST", "NSE:CRISIL", "NSE:CROMPTON", "NSE:CSBBANK", "NSE:CTE", "NSE:CUB", "NSE:CUBEXTUB", "NSE:CUMMINSIND", "NSE:CUPID", "NSE:CURATECH", "NSE:CYBERMEDIA", "NSE:CYBERTECH", "NSE:CYIENT", "NSE:DAAWAT", "NSE:DABUR", "NSE:DALBHARAT", "NSE:DALMIASUG", "NSE:DAMODARIND", "NSE:DATAMATICS", "NSE:DBCORP", "NSE:DBL", "NSE:DBREALTY", "NSE:DBSTOCKBRO", "NSE:DCAL", "NSE:DCBBANK", "NSE:DCM", "NSE:DCMFINSERV", "NSE:DCMNVL", "NSE:DCMSHRIRAM", "NSE:DCW", "NSE:DECCANCE", "NSE:DEEPAKFERT", "NSE:DEEPAKNTR", "NSE:DEEPIND", "NSE:DELTACORP", "NSE:DELTAMAGNT", "NSE:DEN", "NSE:DENORA", "NSE:DFMFOODS", "NSE:DGCONTENT", "NSE:DHAMPURSUG", "NSE:DHANBANK", "NSE:DHANUKA", "NSE:DHARSUGAR", "NSE:DHFL", "NSE:DHUNINV", "NSE:DIAMONDYD", "NSE:DIAPOWER", "NSE:DICIND", "NSE:DIGISPICE", "NSE:DIGJAMLTD", "NSE:DISHTV", "NSE:DIVISLAB", "NSE:DIXON", "NSE:DLF", "NSE:DLINKINDIA", "NSE:DMART", "NSE:DNAMEDIA", "NSE:DOLAT", "NSE:DOLLAR", "NSE:DONEAR", "NSE:DPSCLTD", "NSE:DPWIRES", "NSE:DQE", "NSE:DREDGECORP", "NSE:DRREDDY", "NSE:DSSL", "NSE:DTIL", "NSE:DUCON", "NSE:DVL", "NSE:DWARKESH", "NSE:DYNAMATECH", "NSE:DYNPRO", "NSE:EASTSILK", "NSE:EASUNREYRL", "NSE:ECLERX", "NSE:EDELWEISS", "NSE:EDL", "NSE:EDUCOMP", "NSE:EICHERMOT", "NSE:EIDPARRY", "NSE:EIHAHOTELS", "NSE:EIHOTEL", "NSE:EIMCOELECO", "NSE:EKC", "NSE:ELECON", "NSE:ELECTCAST", "NSE:ELECTHERM", "NSE:ELGIEQUIP", "NSE:ELGIRUBCO", "NSE:EMAMILTD", "NSE:EMAMIPAP", "NSE:EMAMIREAL", "NSE:EMCO", "NSE:EMKAY", "NSE:EMMBI", "NSE:ENDURANCE", "NSE:ENERGYDEV", "NSE:ENGINERSIN", "NSE:ENIL", "NSE:EON", "NSE:EQUITAS", "NSE:ERIS", "NSE:EROSMEDIA", "NSE:ESABINDIA", "NSE:ESCORTS", "NSE:ESSARSHPNG", "NSE:ESSELPACK", "NSE:ESTER", "NSE:EUROCERA", "NSE:EUROMULTI", "NSE:EUROTEXIND", "NSE:EVEREADY", "NSE:EVERESTIND", "NSE:EXCEL", "NSE:EXCELINDUS", "NSE:EXIDEIND", "NSE:EXPLEOSOL", "NSE:FACT", "NSE:FAIRCHEM", "NSE:FCL", "NSE:FCONSUMER", "NSE:FCSSOFT", "NSE:FDC", "NSE:FEDERALBNK", "NSE:FEL", "NSE:FELDVR", "NSE:FIEMIND", "NSE:FILATEX", "NSE:FINCABLES", "NSE:FINEORG", "NSE:FINPIPE", "NSE:FLEXITUFF", "NSE:FLFL", "NSE:FLUOROCHEM", "NSE:FMGOETZE", "NSE:FMNL", "NSE:FORCEMOT", "NSE:FORTIS", "NSE:FOSECOIND", "NSE:FRETAIL", "NSE:FSC", "NSE:FSL", "NSE:GABRIEL", "NSE:GAEL", "NSE:GAIL", "NSE:GAL", "NSE:GALAXYSURF", "NSE:GALLANTT", "NSE:GALLISPAT", "NSE:GAMMNINFRA", "NSE:GANDHITUBE", "NSE:GANECOS", "NSE:GANESHHOUC", "NSE:GANGESSECU", "NSE:GANGOTRI", "NSE:GARDENSILK", "NSE:GARFIBRES", "NSE:GATI", "NSE:GAYAHWS", "NSE:GAYAPROJ", "NSE:GDL", "NSE:GEECEE", "NSE:GENESYS", "NSE:GENUSPAPER", "NSE:GENUSPOWER", "NSE:GEOJITFSL", "NSE:GEPIL", "NSE:GESHIP", "NSE:GET&D", "NSE:GFLLIMITED", "NSE:GHCL", "NSE:GICHSGFIN", "NSE:GICRE", "NSE:GILLANDERS", "NSE:GILLETTE", "NSE:GINNIFILA", "NSE:GIPCL", "NSE:GISOLUTION", "NSE:GKWLIMITED", "NSE:GLAXO", "NSE:GLENMARK", "NSE:GLFL", "NSE:GLOBALVECT", "NSE:GLOBOFFS", "NSE:GLOBUSSPR", "NSE:GMBREW", "NSE:GMDCLTD", "NSE:GMMPFAUDLR", "NSE:GMRINFRA", "NSE:GNA", "NSE:GNFC", "NSE:GOACARBON", "NSE:GOCLCORP", "NSE:GODFRYPHLP", "NSE:GODREJAGRO", "NSE:GODREJCP", "NSE:GODREJIND", "NSE:GODREJPROP", "NSE:GOENKA", "NSE:GOKEX", "NSE:GOKUL", "NSE:GOKULAGRO", "NSE:GOLDENTOBC", "NSE:GOLDIAM", "NSE:GOLDTECH", "NSE:GOODLUCK", "NSE:GPIL", "NSE:GPPL", "NSE:GPTINFRA", "NSE:GRANULES", "NSE:GRAPHITE", "NSE:GRASIM", "NSE:GRAVITA", "NSE:GREAVESCOT", "NSE:GREENLAM", "NSE:GREENPANEL", "NSE:GREENPLY", "NSE:GREENPOWER", "NSE:GRINDWELL", "NSE:GROBTEA", "NSE:GRPLTD", "NSE:GRSE", "NSE:GSCLCEMENT", "NSE:GSFC", "NSE:GSKCONS", "NSE:GSPL", "NSE:GSS", "NSE:GTL", "NSE:GTLINFRA", "NSE:GTNIND", "NSE:GTNTEX", "NSE:GTPL", "NSE:GUFICBIO", "NSE:GUJALKALI", "NSE:GUJAPOLLO", "NSE:GUJGASLTD", "NSE:GUJRAFFIA", "NSE:GULFOILLUB", "NSE:GULFPETRO", "NSE:GULPOLY", "NSE:GVKPIL", "NSE:HAL", "NSE:HARITASEAT", "NSE:HARRMALAYA", "NSE:HATHWAY", "NSE:HATSUN", "NSE:HAVELLS", "NSE:HAVISHA", "NSE:HBLPOWER", "NSE:HBSL", "NSE:HCC", "NSE:HCG", "NSE:HCL-INSYS", "NSE:HCLTECH", "NSE:HDFC", "NSE:HDFCAMC", "NSE:HDFCBANK", "NSE:HDFCLIFE", "NSE:HDIL", "NSE:HEG", "NSE:HEIDELBERG", "NSE:HERCULES", "NSE:HERITGFOOD", "NSE:HEROMOTOCO", "NSE:HESTERBIO", "NSE:HEXATRADEX", "NSE:HEXAWARE", "NSE:HFCL", "NSE:HGINFRA", "NSE:HGS", "NSE:HIKAL", "NSE:HIL", "NSE:HILTON", "NSE:HIMATSEIDE", "NSE:HINDALCO", "NSE:HINDCOMPOS", "NSE:HINDCOPPER", "NSE:HINDMOTORS", "NSE:HINDNATGLS", "NSE:HINDOILEXP", "NSE:HINDPETRO", "NSE:HINDSYNTEX", "NSE:HINDUNILVR", "NSE:HINDZINC", "NSE:HIRECT", "NSE:HISARMETAL", "NSE:HITECH", "NSE:HITECHCORP", "NSE:HITECHGEAR", "NSE:HLVLTD", "NSE:HMT", "NSE:HMVL", "NSE:HNDFDS", "NSE:HONAUT", "NSE:HONDAPOWER", "NSE:HOTELRUGBY", "NSE:HOVS", "NSE:HPL", "NSE:HSCL", "NSE:HSIL", "NSE:HTMEDIA", "NSE:HUBTOWN", "NSE:HUDCO", "NSE:IBREALEST", "NSE:IBULHSGFIN", "NSE:IBULISL", "NSE:IBVENTURES", "NSE:ICICIBANK", "NSE:ICICIGI", "NSE:ICICIPRULI", "NSE:ICIL", "NSE:ICRA", "NSE:IDBI", "NSE:IDEA", "NSE:IDFC", "NSE:IDFCFIRSTB", "NSE:IEX", "NSE:IFBAGRO", "NSE:IFBIND", "NSE:IFCI", "NSE:IFGLEXPOR", "NSE:IGARASHI", "NSE:IGL", "NSE:IGPL", "NSE:IIFL", "NSE:IIFLSEC", "NSE:IIFLWAM", "NSE:IITL", "NSE:IL&FSENGG", "NSE:IL&FSTRANS", "NSE:IMFA", "NSE:IMPAL", "NSE:IMPEXFERRO", "NSE:INDBANK", "NSE:INDHOTEL", "NSE:INDIACEM", "NSE:INDIAGLYCO", "NSE:INDIAMART", "NSE:INDIANB", "NSE:INDIANCARD", "NSE:INDIANHUME", "NSE:INDIGO", "NSE:INDLMETER", "NSE:INDNIPPON", "NSE:INDOCO", "NSE:INDORAMA", "NSE:INDOSOLAR", "NSE:INDOSTAR", "NSE:INDOTECH", "NSE:INDOTHAI", "NSE:INDOWIND", "NSE:INDRAMEDCO", "NSE:INDSWFTLAB", "NSE:INDSWFTLTD", "NSE:INDTERRAIN", "NSE:INDUSINDBK", "NSE:INEOSSTYRO", "NSE:INFIBEAM", "NSE:INFOBEAN", "NSE:INFRATEL", "NSE:INFY", "NSE:INGERRAND", "NSE:INOXLEISUR", "NSE:INOXWIND", "NSE:INSECTICID", "NSE:INSPIRISYS", "NSE:INTEGRA", "NSE:INTELLECT", "NSE:INTENTECH", "NSE:INVENTURE", "NSE:IOB", "NSE:IOC", "NSE:IOLCP", "NSE:IPCALAB", "NSE:IRB", "NSE:IRCON", "NSE:IRCTC", "NSE:ISEC", "NSE:ISFT", "NSE:ISMTLTD", "NSE:ITC", "NSE:ITDC", "NSE:ITDCEM", "NSE:ITI", "NSE:IVC", "NSE:IVP", "NSE:IVRCLINFRA", "NSE:IZMO", "NSE:J&KBANK", "NSE:JAGRAN", "NSE:JAGSNPHARM", "NSE:JAIBALAJI", "NSE:JAICORPLTD", "NSE:JAIHINDPRO", "NSE:JAINSTUDIO", "NSE:JAMNAAUTO", "NSE:JASH", "NSE:JAYAGROGN", "NSE:JAYBARMARU", "NSE:JAYNECOIND", "NSE:JAYSREETEA", "NSE:JBCHEPHARM", "NSE:JBFIND", "NSE:JBMA", "NSE:JCHAC", "NSE:JETAIRWAYS", "NSE:JHS", "NSE:JIKIND", "NSE:JINDALPHOT", "NSE:JINDALPOLY", "NSE:JINDALSAW", "NSE:JINDALSTEL", "NSE:JINDCOT", "NSE:JINDRILL", "NSE:JINDWORLD", "NSE:JISLDVREQS", "NSE:JISLJALEQS", "NSE:JITFINFRA", "NSE:JIYAECO", "NSE:JKCEMENT", "NSE:JKIL", "NSE:JKLAKSHMI", "NSE:JKPAPER", "NSE:JKTYRE", "NSE:JMA", "NSE:JMCPROJECT", "NSE:JMFINANCIL", "NSE:JMTAUTOLTD", "NSE:JOCIL", "NSE:JPASSOCIAT", "NSE:JPINFRATEC", "NSE:JPOLYINVST", "NSE:JPPOWER", "NSE:JSL", "NSE:JSLHISAR", "NSE:JSWENERGY", "NSE:JSWHL", "NSE:JSWSTEEL", "NSE:JTEKTINDIA", "NSE:JUBILANT", "NSE:JUBLFOOD", "NSE:JUBLINDS", "NSE:JUMPNET", "NSE:JUSTDIAL", "NSE:JVLAGRO", "NSE:JYOTHYLAB", "NSE:KABRAEXTRU", "NSE:KAJARIACER", "NSE:KAKATCEM", "NSE:KALPATPOWR", "NSE:KALYANI", "NSE:KALYANIFRG", "NSE:KAMATHOTEL", "NSE:KAMDHENU", "NSE:KANANIIND", "NSE:KANORICHEM", "NSE:KANSAINER", "NSE:KARDA", "NSE:KARMAENG", "NSE:KARURVYSYA", "NSE:KAUSHALYA", "NSE:KAVVERITEL", "NSE:KAYA", "NSE:KCP", "NSE:KCPSUGIND", "NSE:KDDL", "NSE:KEC", "NSE:KECL", "NSE:KEI", "NSE:KELLTONTEC", "NSE:KENNAMET", "NSE:KERNEX", "NSE:KESORAMIND", "NSE:KEYFINSERV", "NSE:KGL", "NSE:KHADIM", "NSE:KHAITANLTD", "NSE:KHANDSE", "NSE:KICL", "NSE:KILITCH", "NSE:KINGFA", "NSE:KIOCL", "NSE:KIRIINDUS", "NSE:KIRLFER", "NSE:KIRLOSBROS", "NSE:KIRLOSENG", "NSE:KIRLOSIND", "NSE:KITEX", "NSE:KKCL", "NSE:KMSUGAR", "NSE:KNRCON", "NSE:KOHINOOR", "NSE:KOKUYOCMLN", "NSE:KOLTEPATIL", "NSE:KOPRAN", "NSE:KOTAKBANK", "NSE:KOTARISUG", "NSE:KOTHARIPET", "NSE:KOTHARIPRO", "NSE:KPITTECH", "NSE:KPRMILL", "NSE:KRBL", "NSE:KREBSBIO", "NSE:KRIDHANINF", "NSE:KRISHANA", "NSE:KSB", "NSE:KSCL", "NSE:KSERASERA", "NSE:KSK", "NSE:KSL", "NSE:KTKBANK", "NSE:KUANTUM", "NSE:KWALITY", "NSE:L&TFH", "NSE:LAKPRE", "NSE:LAKSHVILAS", "NSE:LALPATHLAB", "NSE:LAMBODHARA", "NSE:LAOPALA", "NSE:LASA", "NSE:LAURUSLABS", "NSE:LAXMIMACH", "NSE:LEMONTREE", "NSE:LFIC", "NSE:LGBBROSLTD", "NSE:LGBFORGE", "NSE:LIBAS", "NSE:LIBERTSHOE", "NSE:LICHSGFIN", "NSE:LINCOLN", "NSE:LINCPEN", "NSE:LINDEINDIA", "NSE:LOKESHMACH", "NSE:LOTUSEYE", "NSE:LOVABLE", "NSE:LPDC", "NSE:LSIL", "NSE:LT", "NSE:LTI", "NSE:LTTS", "NSE:LUMAXIND", "NSE:LUMAXTECH", "NSE:LUPIN", "NSE:LUXIND", "NSE:LYKALABS", "NSE:LYPSAGEMS", "NSE:M&M", "NSE:M&MFIN", "NSE:MAANALU", "NSE:MADHAV", "NSE:MADHUCON", "NSE:MADRASFERT", "NSE:MAGADSUGAR", "NSE:MAGMA", "NSE:MAGNUM", "NSE:MAHABANK", "NSE:MAHAPEXLTD", "NSE:MAHASTEEL", "NSE:MAHESHWARI", "NSE:MAHINDCIE", "NSE:MAHLIFE", "NSE:MAHLOG", "NSE:MAHSCOOTER", "NSE:MAHSEAMLES", "NSE:MAITHANALL", "NSE:MAJESCO", "NSE:MALUPAPER", "NSE:MANAKALUCO", "NSE:MANAKCOAT", "NSE:MANAKSIA", "NSE:MANAKSTEEL", "NSE:MANALIPETC", "NSE:MANAPPURAM", "NSE:MANGALAM", "NSE:MANGCHEFER", "NSE:MANGLMCEM", "NSE:MANGTIMBER", "NSE:MANINDS", "NSE:MANINFRA", "NSE:MANUGRAPH"};

	static KiteConnect kiteConnect;
	public static Map<String, Quote> instrumentsOld=new HashMap<String, Quote>();
	public static Map<String, Quote> instrumentsNew=new HashMap<String, Quote>();
	public static Map<String, Quote> instrumentsTrending=new HashMap<String, Quote>();
	int Count=0;

	public static void main(String[] args) {
		SpringApplication.run(RoboTradeApplication.class, args);
	}
	
	/*public RoboTradeApplication () {
		
		UserAuthentication loginToKite=new UserAuthentication();
		try {
			kiteConnect=loginToKite.userLogin();
			 KiteApiServices apiService=new KiteApiServices();
				
					apiService.getLTP(kiteConnect);
			 


			
		} catch (JSONException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (KiteException e) {
			e.printStackTrace();
		}
		
	}*/
	
	/*//@Scheduled(cron = "0 3 0 * * ?")
	@Scheduled(fixedDelay = 12000)
	public void findTrandingStocks() {
		KiteConnectController kiteController=new KiteConnectController();
		try {
			
			
			instrumentsNew=kiteController.getNSEStockQuote(kiteConnect,instrumentsNew);
			kiteController.comparethePriceWithOld(instrumentsNew,instrumentsOld,instrumentsTrending);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (KiteException e) {
			e.printStackTrace();
		}
	
	}*/
	
	@Scheduled(fixedDelay = 120000)
	public void findStocksAbove200() {
		if(Count==0) {
			UserAuthentication loginToKite=new UserAuthentication();
			try {
				kiteConnect=loginToKite.userLogin();
			} catch (JSONException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (KiteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			Count++;
				 
		}
		 KiteApiServices apiService=new KiteApiServices();
		try {
			apiService.getLTP(kiteConnect);
	 	} catch (IOException e) {
			e.printStackTrace();
		} catch (KiteException e) {
			e.printStackTrace();
		}

	//beginTrading();

}
	
}
